# Generated by Django 5.1.4 on 2025-01-11 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "last_accessed",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "N",
                    models.PositiveIntegerField(
                        choices=[(5, "5"), (7, "7"), (9, "9"), (11, "11")], default=5
                    ),
                ),
                ("message_int", models.BigIntegerField(default=-1, editable=False)),
                ("_data", models.CharField(max_length=2048)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("message_int",),
                        name="unique_active_message_int",
                    )
                ],
            },
        ),
    ]
